#!/usr/bin/env python3
"""
Copy every application table from the local SQLite file into PostgreSQL (Neon).

Read-only against SQLite -- it never writes back, and it does not touch
``backend/db.py`` or any app code. The app still runs on SQLite after this;
this script only populates the Postgres side.

The Postgres schema mirrors the SQLite DDL in ``data/budget.sqlite``
column-for-column (types, PRIMARY KEY, UNIQUE, CHECK, and FOREIGN KEY):

  - INTEGER PRIMARY KEY AUTOINCREMENT -> INTEGER GENERATED BY DEFAULT AS
    IDENTITY (sequence resynced from MAX(id) after the copy)
  - REAL                 -> DOUBLE PRECISION
  - NUMERIC(p, s)        -> NUMERIC(p, s)
  - BOOLEAN (0/1)        -> BOOLEAN
  - TEXT                 -> TEXT
  - SQLite TEXT columns that actually hold dates (start_date, finish_date,
    statement_date, due_date, payment_date) -> DATE, and the ones holding
    clock times (the travel *_time columns) -> TIME. See note 4.
  - DATE                 -> DATE, ISO-8601 (YYYY-MM-DD)
  - TIMESTAMP            -> TIMESTAMPTZ(0) (see notes 3 and 4)
  - BLOB (payslip PDFs)  -> BYTEA

Four deliberate departures from a literal translation:

  1. ``app_user.username`` is ``UNIQUE COLLATE NOCASE`` in SQLite, which has
     no direct Postgres equivalent on a plain TEXT column. The case-
     insensitive *uniqueness* is preserved with a UNIQUE INDEX on
     ``LOWER(username)``. Case-insensitive *lookups* (``WHERE username = ?``
     matching a different case) are NOT preserved -- Postgres compares TEXT
     case-sensitively -- so queries need ``LOWER(username) = LOWER(?)`` when
     the API is eventually pointed at Postgres.
  2. Identity sequences are resynced from ``MAX(id)``, not from
     ``sqlite_sequence``, because this database has duplicate
     ``sqlite_sequence`` rows for several tables (e.g. two
     ``calendar_day_override`` rows, 557 and 456) and the lower/stale value
     would hand out colliding ids on the first Postgres insert.
  3. The SQLite ``TIMESTAMP`` columns hold two different formats, because
     two different writers produced them: 1,903 naive ``YYYY-MM-DD HH:MM:SS``
     values from SQLite's own ``CURRENT_TIMESTAMP`` default (which is UTC),
     and 201 timezone-aware ISO-8601 values written by the app from Python
     (all of them ``+00:00``). Every value is therefore UTC, so the columns
     become ``TIMESTAMPTZ`` and the session is pinned to UTC for the copy --
     that reads the naive strings as UTC and keeps the offset on the aware
     ones. Plain ``TIMESTAMP`` would silently drop the ``+00:00`` and leave
     the column's meaning dependent on the reader's timezone.
  4. Types are the normalised ones, so a rebuild from SQLite lands on exactly
     the schema ``backend/scripts/normalize_time_types.py`` produced rather
     than quietly reverting it:

       - timestamps are ``TIMESTAMPTZ(0)`` (whole seconds). Those two SQLite
         writers also disagreed on precision -- microseconds on 201 rows, none
         on the other 1,903 -- and since ``.isoformat()`` omits a zero
         fraction, one column rendered two different shapes. Pinning the
         precision is what stops the next INSERT reintroducing the split.
       - the date/time-bearing TEXT columns get real DATE/TIME types, so
         Postgres validates and compares them and the API renders ISO-8601
         (note this makes a stored ``'07:15'`` render as ``'07:15:00'``).

Foreign keys are added AFTER the data load rather than inline, so the copy
does not depend on insertion order and every FK is validated against the
real data as it is created.

Usage (from the repo root, with the venv active):

    python backend/scripts/migrate_sqlite_to_postgres.py

Reads the Postgres connection from ``.env.local`` at the repo root
(``DATABASE_URL_UNPOOLED`` preferred over ``DATABASE_URL``: the unpooled
endpoint avoids the pgbouncer session limits that bite on DDL and large
batched inserts). Note that ``DATABASE_URL`` in ``.env.local`` is the
Postgres URL, while ``backend/db.py`` reads ``DATABASE_URL`` as a *SQLite*
path from ``.env`` -- this script never exports it, so the two cannot
collide.

Options:

    --sqlite PATH     source SQLite file (default: <repo-root>/data/budget.sqlite)
    --pg URL          target Postgres URL (default: from --env-file)
    --env-file PATH   env file to read the URL from (default: .env.local)
    --replace         DROP and recreate tables that already exist
    --dry-run         create nothing; report what would be copied
"""

from __future__ import annotations

import argparse
import sqlite3
import sys
from pathlib import Path

_SCRIPTS_DIR = Path(__file__).resolve().parent
_BACKEND_DIR = _SCRIPTS_DIR.parent
_REPO_ROOT = _BACKEND_DIR.parent
_DEFAULT_SQLITE_PATH = _REPO_ROOT / "data" / "budget.sqlite"
_DEFAULT_ENV_FILE = _REPO_ROOT / ".env.local"

# Tables in dependency order. FKs are applied separately (see _FOREIGN_KEYS),
# so this order only governs a tidy create/copy sequence and the drop order
# is simply its reverse.
_SCHEMA: list[tuple[str, str]] = [
    (
        "_app_meta",
        """
        key   TEXT PRIMARY KEY,
        value TEXT
        """,
    ),
    (
        "app_user",
        """
        id            INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        username      TEXT NOT NULL,
        password_hash TEXT NOT NULL,
        created_at    TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CHECK (length(trim(username)) > 0)
        """,
    ),
    (
        "blood_pressure",
        """
        id          INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        systolic    INTEGER,
        diastolic   INTEGER,
        pulse       INTEGER,
        spo2        INTEGER,
        temperature NUMERIC(5, 2),
        weight      NUMERIC(6, 2),
        notes       TEXT,
        created_at  TIMESTAMPTZ(0) DEFAULT CURRENT_TIMESTAMP
        """,
    ),
    (
        "calendar_day_override",
        """
        id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        day        DATE UNIQUE,
        amount     DOUBLE PRECISION,
        created_at TIMESTAMPTZ(0) DEFAULT CURRENT_TIMESTAMP
        """,
    ),
    (
        "credit_card",
        """
        id                     INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name                   TEXT,
        credit_limit           DOUBLE PRECISION,
        last_statement_balance DOUBLE PRECISION DEFAULT 0,
        current_balance        DOUBLE PRECISION DEFAULT 0,
        minimum_due            DOUBLE PRECISION DEFAULT 0,
        interest_rate          DOUBLE PRECISION DEFAULT 3.5,
        statement_date         DATE,
        due_date               DATE,
        created_at             TIMESTAMPTZ(0) DEFAULT CURRENT_TIMESTAMP
        """,
    ),
    (
        "credit_card_payment",
        """
        id             INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        credit_card_id INTEGER,
        amount         DOUBLE PRECISION,
        payment_date   DATE,
        note           TEXT,
        created_at     TIMESTAMPTZ(0) DEFAULT CURRENT_TIMESTAMP
        """,
    ),
    (
        "fixed_expense",
        """
        id           INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        period_half  INTEGER,
        period_year  INTEGER,
        period_month INTEGER,
        amount       DOUBLE PRECISION,
        description  TEXT,
        created_at   TIMESTAMPTZ(0) DEFAULT CURRENT_TIMESTAMP
        """,
    ),
    (
        "house_payment",
        """
        id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name       TEXT,
        notes      TEXT,
        created_at TIMESTAMPTZ(0) DEFAULT CURRENT_TIMESTAMP
        """,
    ),
    (
        "house_payment_entry",
        """
        id               INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        house_payment_id INTEGER,
        paid_on          DATE,
        amount           DOUBLE PRECISION,
        created_at       TIMESTAMPTZ(0) DEFAULT CURRENT_TIMESTAMP
        """,
    ),
    (
        "installment",
        """
        id                  INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name                TEXT,
        installment_current INTEGER,
        installment_total   INTEGER,
        principal           DOUBLE PRECISION,
        interest            DOUBLE PRECISION,
        payment_total       DOUBLE PRECISION,
        start_date          DATE,
        finish_date         DATE,
        remaining           DOUBLE PRECISION,
        original_total      DOUBLE PRECISION,
        credit_card_id      INTEGER,
        created_at          TIMESTAMPTZ(0) DEFAULT CURRENT_TIMESTAMP
        """,
    ),
    (
        "installment_line",
        """
        id             INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        installment_id INTEGER,
        seq            INTEGER,
        principal      DOUBLE PRECISION DEFAULT 0,
        interest       DOUBLE PRECISION,
        payment_total  DOUBLE PRECISION,
        UNIQUE (installment_id, seq)
        """,
    ),
    (
        "lotto_draw",
        """
        id            INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        draw_date     DATE NOT NULL UNIQUE,
        n1            INTEGER,
        n2            INTEGER,
        n3            INTEGER,
        n4            INTEGER,
        n5            INTEGER,
        n6            INTEGER,
        created_at    TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        jackpot_prize DOUBLE PRECISION,
        winners       INTEGER NOT NULL DEFAULT 0,
        CHECK (
            (n1 IS NULL AND n2 IS NULL AND n3 IS NULL AND n4 IS NULL AND n5 IS NULL AND n6 IS NULL)
            OR (n1 >= 1 AND n1 < n2 AND n2 < n3 AND n3 < n4 AND n4 < n5 AND n5 < n6 AND n6 <= 58)
        )
        """,
    ),
    (
        "lotto_attempt",
        """
        id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        draw_id    INTEGER NOT NULL,
        n1         INTEGER NOT NULL,
        n2         INTEGER NOT NULL,
        n3         INTEGER NOT NULL,
        n4         INTEGER NOT NULL,
        n5         INTEGER NOT NULL,
        n6         INTEGER NOT NULL,
        created_at TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        ticket     INTEGER,
        hidden     INTEGER NOT NULL DEFAULT 0,
        CHECK (n1 >= 1 AND n1 < n2 AND n2 < n3 AND n3 < n4 AND n4 < n5 AND n5 < n6 AND n6 <= 58)
        """,
    ),
    (
        "monthly_expense",
        """
        id           INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name         TEXT,
        description  TEXT,
        amount       DOUBLE PRECISION,
        period_half  INTEGER,
        period_year  INTEGER,
        period_month INTEGER,
        is_recurring BOOLEAN DEFAULT FALSE,
        created_at   TIMESTAMPTZ(0) DEFAULT CURRENT_TIMESTAMP
        """,
    ),
    (
        "pay_period_start_override",
        """
        id           INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        period_year  INTEGER,
        period_month INTEGER,
        period_half  INTEGER,
        start_date   DATE,
        created_at   TIMESTAMPTZ(0) DEFAULT CURRENT_TIMESTAMP,
        UNIQUE (period_year, period_month, period_half)
        """,
    ),
    (
        "payslip",
        """
        id                    INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        total                 DOUBLE PRECISION,
        commission            DOUBLE PRECISION,
        reimbursement         DOUBLE PRECISION,
        medical_reimbursement DOUBLE PRECISION,
        others                DOUBLE PRECISION,
        mp2                   DOUBLE PRECISION,
        allowances            DOUBLE PRECISION,
        thirteenth_month      DOUBLE PRECISION,
        basic_salary          DOUBLE PRECISION,
        period_year           INTEGER,
        period_month          INTEGER,
        period_half           INTEGER,
        notes                 TEXT,
        withholding_tax       DOUBLE PRECISION,
        sss_contribution      DOUBLE PRECISION,
        philhealth            DOUBLE PRECISION,
        pag_ibig              DOUBLE PRECISION,
        pdf_data              BYTEA,
        created_at            TIMESTAMPTZ(0) DEFAULT CURRENT_TIMESTAMP,
        employee_hdmf         DOUBLE PRECISION,
        sss                   DOUBLE PRECISION
        """,
    ),
    (
        "payslip_default",
        """
        half                  INTEGER PRIMARY KEY,
        period_year           TEXT NOT NULL DEFAULT '',
        period_month          TEXT NOT NULL DEFAULT '',
        total                 TEXT NOT NULL DEFAULT '',
        basic_salary          TEXT NOT NULL DEFAULT '',
        commission            TEXT NOT NULL DEFAULT '',
        reimbursement         TEXT NOT NULL DEFAULT '',
        medical_reimbursement TEXT NOT NULL DEFAULT '',
        others                TEXT NOT NULL DEFAULT '',
        mp2                   TEXT NOT NULL DEFAULT '',
        allowances            TEXT NOT NULL DEFAULT '',
        thirteenth_month      TEXT NOT NULL DEFAULT '',
        notes                 TEXT NOT NULL DEFAULT '',
        withholding_tax       TEXT NOT NULL DEFAULT '',
        sss_contribution      TEXT NOT NULL DEFAULT '',
        philhealth            TEXT NOT NULL DEFAULT '',
        pag_ibig              TEXT NOT NULL DEFAULT '',
        updated_at            TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CHECK (half IN (1, 2))
        """,
    ),
    (
        "payslip_default_settings",
        """
        id            INTEGER PRIMARY KEY,
        settings_half TEXT NOT NULL DEFAULT 'first',
        CHECK (id = 1),
        CHECK (settings_half IN ('first', 'second'))
        """,
    ),
    (
        "travel_trip",
        """
        id              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        title           TEXT NOT NULL,
        entry_year      INTEGER NOT NULL,
        entry_month     INTEGER NOT NULL,
        notes           TEXT,
        created_at      TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        entry_month_end INTEGER,
        CHECK (length(trim(title)) > 0),
        CHECK (entry_month BETWEEN 1 AND 12)
        """,
    ),
    (
        "travel_accommodation",
        """
        id                   INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        trip_id              INTEGER NOT NULL,
        name                 TEXT NOT NULL,
        checkin_date         DATE NOT NULL,
        checkout_date        DATE NOT NULL,
        checkin_time         TIME,
        checkout_time        TIME,
        booking_confirmation TEXT,
        instructions         TEXT,
        location_name        TEXT,
        location_map_url     TEXT,
        notes                TEXT,
        created_at           TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CHECK (length(trim(name)) > 0),
        CHECK (checkout_date >= checkin_date)
        """,
    ),
    (
        "travel_flight",
        """
        id             INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        trip_id        INTEGER NOT NULL,
        flight_number  TEXT NOT NULL,
        flight_date    DATE,
        departure_time TIME,
        arrival_time   TIME,
        from_location  TEXT,
        from_map_url   TEXT,
        to_location    TEXT,
        to_map_url     TEXT,
        notes          TEXT,
        created_at     TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CHECK (length(trim(flight_number)) > 0)
        """,
    ),
    (
        "travel_itinerary",
        """
        id               INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        trip_id          INTEGER NOT NULL,
        item_date        DATE NOT NULL,
        start_time       TIME,
        end_time         TIME,
        activity         TEXT NOT NULL,
        location_name    TEXT,
        location_map_url TEXT,
        notes            TEXT,
        created_at       TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        item_end_date    DATE,
        CHECK (length(trim(activity)) > 0)
        """,
    ),
    (
        "travel_transport",
        """
        id             INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        trip_id        INTEGER NOT NULL,
        -- Ground transport leg: bus or train. Same shape as travel_flight,
        -- with a mode and an optional (rather than required) number, since
        -- a bus route is not always known/labeled the way a flight is.
        mode           TEXT NOT NULL,
        number         TEXT,
        travel_date    DATE,
        departure_time TIME,
        arrival_time   TIME,
        from_location  TEXT,
        from_map_url   TEXT,
        to_location    TEXT,
        to_map_url     TEXT,
        notes          TEXT,
        created_at     TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CHECK (mode IN ('bus', 'train'))
        """,
    ),
]

# (table, column, target table, target column, ON DELETE action)
_FOREIGN_KEYS = [
    ("credit_card_payment", "credit_card_id", "credit_card", "id", "CASCADE"),
    ("house_payment_entry", "house_payment_id", "house_payment", "id", "CASCADE"),
    ("installment", "credit_card_id", "credit_card", "id", "SET NULL"),
    ("installment_line", "installment_id", "installment", "id", "CASCADE"),
    ("lotto_attempt", "draw_id", "lotto_draw", "id", "CASCADE"),
    ("travel_accommodation", "trip_id", "travel_trip", "id", "CASCADE"),
    ("travel_flight", "trip_id", "travel_trip", "id", "CASCADE"),
    ("travel_itinerary", "trip_id", "travel_trip", "id", "CASCADE"),
    ("travel_transport", "trip_id", "travel_trip", "id", "CASCADE"),
]

_INDEXES = [
    # Preserves app_user.username's SQLite COLLATE NOCASE uniqueness.
    "CREATE UNIQUE INDEX idx_app_user_username_lower ON app_user (LOWER(username))",
    "CREATE INDEX idx_blood_pressure_created ON blood_pressure (created_at DESC)",
    "CREATE INDEX idx_credit_card_payment_parent ON credit_card_payment (credit_card_id, payment_date DESC)",
    "CREATE INDEX idx_fixed_expense_period ON fixed_expense (period_year, period_month, period_half, created_at DESC)",
    "CREATE INDEX idx_house_payment_created ON house_payment (created_at DESC)",
    "CREATE INDEX idx_house_payment_name ON house_payment (name)",
    "CREATE INDEX idx_house_payment_entry_parent ON house_payment_entry (house_payment_id, paid_on DESC)",
    "CREATE INDEX idx_installment_created ON installment (created_at DESC)",
    "CREATE INDEX idx_installment_credit_card_id ON installment (credit_card_id)",
    "CREATE INDEX idx_installment_finish_name ON installment (finish_date, name)",
    "CREATE INDEX idx_installment_line_parent ON installment_line (installment_id)",
    "CREATE INDEX idx_lotto_attempt_parent ON lotto_attempt (draw_id, created_at)",
    "CREATE INDEX idx_lotto_draw_date ON lotto_draw (draw_date DESC)",
    "CREATE INDEX idx_monthly_expense_period ON monthly_expense (period_year, period_month, period_half, created_at DESC)",
    "CREATE INDEX idx_payslip_created ON payslip (created_at DESC)",
    "CREATE INDEX idx_payslip_period_sort ON payslip (period_year DESC, period_month DESC, period_half DESC, created_at DESC)",
    "CREATE INDEX idx_travel_accommodation_parent ON travel_accommodation (trip_id, checkin_date, created_at)",
    "CREATE INDEX idx_travel_flight_parent ON travel_flight (trip_id, flight_date, created_at)",
    "CREATE INDEX idx_travel_itinerary_parent ON travel_itinerary (trip_id, item_date, start_time, created_at)",
    "CREATE INDEX idx_travel_transport_parent ON travel_transport (trip_id, travel_date, created_at)",
    "CREATE INDEX idx_travel_trip_period ON travel_trip (entry_year DESC, entry_month DESC, id DESC)",
]

# Tables whose id is AUTOINCREMENT in SQLite, so the Postgres identity
# sequence has to be moved past the copied ids.
_IDENTITY_TABLES = [
    "app_user", "blood_pressure", "calendar_day_override", "credit_card",
    "credit_card_payment", "fixed_expense", "house_payment",
    "house_payment_entry", "installment", "installment_line", "lotto_attempt",
    "lotto_draw", "monthly_expense", "pay_period_start_override", "payslip",
    "travel_accommodation", "travel_flight", "travel_itinerary",
    "travel_transport", "travel_trip",
]

# Columns needing a Python-side conversion: SQLite hands back ints for
# BOOLEAN and bytes for BLOB, neither of which Postgres accepts as-is.
_BOOL_COLUMNS = {("monthly_expense", "is_recurring")}
_BYTEA_COLUMNS = {("payslip", "pdf_data")}

# SQLite kept these as TEXT, so an "empty" value could be stored as '' rather
# than NULL. Postgres will not cast '' to DATE/TIME, so map it to NULL on the
# way in. (The current file has none, but the copy should not depend on that.)
_BLANK_TO_NULL_COLUMNS = {
    ("credit_card", "statement_date"), ("credit_card", "due_date"),
    ("credit_card_payment", "payment_date"),
    ("installment", "start_date"), ("installment", "finish_date"),
    ("travel_accommodation", "checkin_time"), ("travel_accommodation", "checkout_time"),
    ("travel_flight", "departure_time"), ("travel_flight", "arrival_time"),
    ("travel_itinerary", "start_time"), ("travel_itinerary", "end_time"),
    ("travel_transport", "departure_time"), ("travel_transport", "arrival_time"),
}


def _table_names() -> list[str]:
    return [name for name, _ in _SCHEMA]


def _resolve_pg_url(env_file: Path, explicit: str | None) -> str:
    if explicit:
        return explicit
    try:
        from dotenv import dotenv_values
    except ImportError:
        sys.exit("python-dotenv is required to read the env file; pass --pg instead")
    if not env_file.is_file():
        sys.exit(f"env file not found: {env_file} (pass --pg URL instead)")
    values = dotenv_values(env_file)
    # Unpooled first: the pooled (pgbouncer) endpoint is unfriendly to DDL
    # and to the large batched inserts this script issues.
    url = (values.get("DATABASE_URL_UNPOOLED") or values.get("DATABASE_URL") or "").strip()
    if not url:
        sys.exit(f"no DATABASE_URL_UNPOOLED or DATABASE_URL in {env_file}")
    if not url.startswith(("postgres://", "postgresql://")):
        sys.exit(f"{env_file} DATABASE_URL is not a Postgres URL")
    return url


def _sqlite_columns(scon: sqlite3.Connection, table: str) -> list[str]:
    return [r[1] for r in scon.execute(f'PRAGMA table_info("{table}")')]


def _convert(table: str, columns: list[str], rows: list[tuple]) -> list[tuple]:
    """Adapt SQLite values that Postgres will not take as-is."""
    import psycopg2

    bool_idx = [i for i, c in enumerate(columns) if (table, c) in _BOOL_COLUMNS]
    blob_idx = [i for i, c in enumerate(columns) if (table, c) in _BYTEA_COLUMNS]
    blank_idx = [i for i, c in enumerate(columns) if (table, c) in _BLANK_TO_NULL_COLUMNS]
    if not bool_idx and not blob_idx and not blank_idx:
        return rows
    out = []
    for row in rows:
        r = list(row)
        for i in bool_idx:
            if r[i] is not None:
                r[i] = bool(r[i])
        for i in blob_idx:
            if r[i] is not None:
                r[i] = psycopg2.Binary(r[i])
        for i in blank_idx:
            if isinstance(r[i], str) and not r[i].strip():
                r[i] = None
        out.append(tuple(r))
    return out


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Copy the SQLite budget database into PostgreSQL."
    )
    ap.add_argument("--sqlite", type=Path, default=_DEFAULT_SQLITE_PATH)
    ap.add_argument("--pg", default=None)
    ap.add_argument("--env-file", type=Path, default=_DEFAULT_ENV_FILE)
    ap.add_argument("--replace", action="store_true", help="DROP and recreate existing tables")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    try:
        import psycopg2
        from psycopg2.extras import execute_values
    except ImportError:
        sys.exit("psycopg2 is required: pip install psycopg2-binary")

    if not args.sqlite.is_file():
        sys.exit(f"SQLite file not found: {args.sqlite}")
    pg_url = _resolve_pg_url(args.env_file, args.pg)

    scon = sqlite3.connect(f"file:{args.sqlite}?mode=ro", uri=True)
    src_counts = {
        t: scon.execute(f'SELECT COUNT(*) FROM "{t}"').fetchone()[0] for t in _table_names()
    }
    print(f"source: {args.sqlite}")
    print(f"target: {pg_url.split('@')[1].split('/')[0]}")
    print(f"tables: {len(_SCHEMA)}, rows: {sum(src_counts.values()):,}\n")

    if args.dry_run:
        for t in _table_names():
            print(f"  would copy {t:28} {src_counts[t]:>6,} rows")
        scon.close()
        return 0

    pcon = psycopg2.connect(pg_url)
    pcon.autocommit = False
    cur = pcon.cursor()
    try:
        # The naive SQLite timestamps are UTC; pin the session so Postgres
        # reads them as UTC rather than as whatever the client's zone is.
        cur.execute("SET TIME ZONE 'UTC'")
        cur.execute(
            "SELECT tablename FROM pg_tables WHERE schemaname='public' AND tablename = ANY(%s)",
            (_table_names(),),
        )
        existing = [r[0] for r in cur.fetchall()]
        if existing and not args.replace:
            sys.exit(
                f"target already has {len(existing)} of these tables "
                f"({', '.join(existing[:5])}{'...' if len(existing) > 5 else ''}).\n"
                "Re-run with --replace to drop and recreate them."
            )
        if existing:
            print(f"dropping {len(existing)} existing table(s)")
            for t in reversed(_table_names()):
                cur.execute(f'DROP TABLE IF EXISTS "{t}" CASCADE')

        print("creating tables")
        for name, body in _SCHEMA:
            cur.execute(f'CREATE TABLE "{name}" (\n{body}\n)')

        print("copying rows")
        copied: dict[str, int] = {}
        for table in _table_names():
            cols = _sqlite_columns(scon, table)
            collist = ", ".join(f'"{c}"' for c in cols)
            total = 0
            cursor = scon.execute(f'SELECT {collist} FROM "{table}"')
            # payslip carries multi-hundred-KB PDFs; a smaller page keeps the
            # single INSERT statement well under Postgres' limits.
            page = 50 if table == "payslip" else 1000
            while True:
                rows = cursor.fetchmany(page)
                if not rows:
                    break
                execute_values(
                    cur,
                    f'INSERT INTO "{table}" ({collist}) VALUES %s',
                    _convert(table, cols, rows),
                    page_size=page,
                )
                total += len(rows)
            copied[table] = total
            print(f"  {table:28} {total:>6,}")

        print("adding foreign keys")
        for tbl, col, ref_tbl, ref_col, on_delete in _FOREIGN_KEYS:
            cur.execute(
                f'ALTER TABLE "{tbl}" ADD CONSTRAINT "fk_{tbl}_{col}" '
                f'FOREIGN KEY ("{col}") REFERENCES "{ref_tbl}" ("{ref_col}") '
                f"ON DELETE {on_delete}"
            )

        print("creating indexes")
        for stmt in _INDEXES:
            cur.execute(stmt)

        print("resyncing identity sequences")
        for table in _IDENTITY_TABLES:
            cur.execute(
                f"SELECT setval(pg_get_serial_sequence('{table}', 'id'), "
                f'COALESCE((SELECT MAX(id) FROM "{table}"), 1), '
                f'(SELECT COUNT(*) FROM "{table}") > 0)'
            )

        mismatches = [t for t in _table_names() if copied[t] != src_counts[t]]
        if mismatches:
            raise RuntimeError(f"row count mismatch, rolling back: {mismatches}")

        pcon.commit()
        print(f"\ncommitted {sum(copied.values()):,} rows across {len(copied)} tables")
    except Exception:
        pcon.rollback()
        print("\nROLLED BACK - no changes were made to Postgres", file=sys.stderr)
        raise
    finally:
        cur.close()
        pcon.close()
        scon.close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
